### ISSUE TITLE
Character duplication and possible explanation

### ISSUE THREAD

**Issue by qeoakes** [CncAnon1/TavernAITurbo#2]
Not sure if this is a bug in the main-line tavernai as well (I see a reference to 'malicious characters' but I'm not sure it's malicious, or the same bug, and I only use this fork). There is a bug involving characters overwriting other characters. I suspect it has to do with using arrow keys after having selected the character from the character menu. I suspect this because I've seen the character icon change while using the arrow keys to navigate through text fields, and the characters duplicated/autosaved over are always alphabetically adjacent. This also matches with character autosaving/live updating - but we're accidentally selecting different characters, from the character editing screen, using arrow keys.

For the time being, I would strongly recommend other users backup their character cards to avoid overwriting.

**Comment by CncAnon1** [comment]
I already know about this bug, but thanks for letting me know that it's related to pressing arrow keys! Maybe I can finally fix it.

**Comment by qeoakes** [comment]
Just saw your push re: character corruption from the editing tool (which I have used). I don't have confirmation that all the cards I have seen that corrupted other cards were created by the tool, but after a brief bit of testing with the characters that over-wrote others, I haven't had any further cloning/corruption. I'll keep an eye out, but it looks promising. Thank you!
